name = "HeavisideSeriesODE"
uuid = "7c0dc5e0-afc9-486c-8b1a-d566789cda8c"
authors = ["Eduardo Lenz Cardoso and Matheus Janczkowski Fogaça"]
version = "1.0.0-DEV"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[compat]
julia = "1.9"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
